components:
  - label: comments
    prompts:
      - type: system
        path: prompts/comments-system-1
  - label: summary
    prompts:
      - type: system
        path: prompts/common-system-1
      - type: user
        path: prompts/summary-user-1
  - label: issues
    prompts:
      - type: system
        path: prompts/common-system-1
      - type: user
        path: prompts/issues-user-1
  - label: testing
    prompts:
      - type: system
        path: prompts/common-system-1
      - type: user
        path: prompts/testing-user-1
  - label: performance
    prompts:
      - type: system
        path: prompts/common-system-1
      - type: user
        path: prompts/performance-user-1
  - label: security
    prompts:
      - type: system
        path: prompts/common-system-1
      - type: user
        path: prompts/security-user-1
gpt:
  model: gpt-4o